const DD_TYPE_FREE_TEXT = 'free_text';
const DD_TYPE_IMAGE = 'image';
const DD_TYPE_NOTE = 'note';

const DD_TYPE_QUERY_TABLE = 'query_table';
const DD_TYPE_QUERY_VALUE = 'query_value';
const DD_TYPE_IFRAME = 'iframe';
const DD_TYPE_HEATMAP = 'heatmap';
const DD_TYPE_DISTRIBUTION = 'distribution';
const DD_TYPE_TOP_LIST = 'toplist';
const DD_TYPE_CHANGE = 'change';

// TIMESERIES
const DD_DISPLAY_TYPE_TIMESERIES_LINE = 'line';
const DD_DISPLAY_TYPE_TIMESERIES_AREA = 'area';
const DD_DISPLAY_TYPE_TIMESERIES_BARS = 'bars';
const DD_TYPE_TIMESERIES = 'timeseries';

const DD_ATTRIBUTE_VARIABLES = 'dd_variables';

export {
  DD_TYPE_FREE_TEXT,
  DD_TYPE_IMAGE,
  DD_TYPE_NOTE,
  DD_TYPE_TIMESERIES,
  DD_DISPLAY_TYPE_TIMESERIES_LINE,
  DD_DISPLAY_TYPE_TIMESERIES_AREA,
  DD_DISPLAY_TYPE_TIMESERIES_BARS,
  DD_TYPE_QUERY_TABLE,
  DD_TYPE_QUERY_VALUE,
  DD_TYPE_IFRAME,
  DD_TYPE_HEATMAP,
  DD_TYPE_DISTRIBUTION,
  DD_TYPE_TOP_LIST,
  DD_TYPE_CHANGE,
  DD_ATTRIBUTE_VARIABLES
};
